### ISSUE TITLE
tapout rails problem

### ISSUE THREAD

**Issue by kswope** [rubyworks/minitap#3]
Maybe its not as simple as putting in my rails test_helper.rb

```
require 'minitap'
MiniTest::Unit.runner = MiniTest::TapY.new
```

But I do get some nicely formatted output, which reports on a bug that seems to come from tapout.  I'll past a portion of the output below

```
NoMethodError

undefined method `options' for #<MiniTest::TestRunner:0x00000002f0e400>

/usr/lib/ruby/1.9.1/test/unit/testcase.rb:16
       13       end
       14 
       15       def run runner
    => 16         @options = runner.options
       17         super runner
       18       end
       19 
```

**Comment by trans** [comment]
Thanks for reporting. Seems I fixed this a couple of months ago but never pushed the release. Try updating to minitap v0.3.5 and let me know if they fixes it for you.

**Comment by trans** [comment]
On the other hand, the issue I just fixed might not be the same problem. What version of MiniTest are you using?

**Comment by kswope** [comment]
I just installed it for the first time a few hours ago, so I guess its the latest.

**Comment by trans** [comment]
I was just thinking about this: 

```
undefined method `options' for #<MiniTest::TestRunner:0x00000002f0e400>
```

Seems to me the `runner` should be an instance of `MiniTest::TapY`, so I am wondering if your test_helper.rb is getting loaded at all, or if the test runner is getting set elsewhere (again). Of course, even so you would think it wouldn't be missing `#options`.

**Comment by kswope** [comment]
I've confirmed that its getting loaded just by writing to a log file, and its just the standard test_helper.rb in a rails app.

I should add that this is just the beginning of a rails app, so there's not much crazy going on yet, I'll try to reproduce the problem with a vanilla rails app.

**Comment by kswope** [comment]
Yep, just a vanilla rails app, with one model and one test.

Put this in Gemfile

```
gem 'minitap'
```

Put this in test_helper.rb

```
require 'minitap'
MiniTest::Unit.runner = MiniTest::TapY.new
```

Results in above reported error.  Perhaps thats the wrong setup to use.  Causing that scoping issue you pointed out.

**Comment by trans** [comment]
Ok. Thanks. I'll have a look at it tomorrow. I'm too tired to get my mind around it tonight. Looking at the code I think I'll spend a day reworking some of it anyway.

**Comment by trans** [comment]
I still can't seem to get the same error you are getting, but I have reworked the code and I am no longer getting the error I was getting ;-) However there is still one bug I have to work out. Hopefully I'll have a new release out by tomorrow.

**Comment by kswope** [comment]
Are you trying to reproduce the problem in RoR? 

I'm consistently reproducing this problem both on Ubuntu and OSX, with the latest version of rails.

I'll dig into it some more today and see if I can be more helpful.  At least I could give you a more detailed recipe for recreating the problem.

**Comment by trans** [comment]
Yes. Weird isn't it. It always amazes me how something seemingly identical can turn out with different results. But there are many subtitles in programming --especially with everything that's going on in an Rails project.

Let's do this. By tomorrow afternoon I am going to release v0.4.0 which is a pretty substantial refactorization. Let's see how that fairs. I was able to get it to run in a basic Rails project, so it looks promising from my end. Lets see if it works on your end. If you run into any issues then what will do is create a temporary github project so I can work off the same code base as you.

https://travis-ci.org/rubyworks/minitap/builds/5559287

**Comment by kswope** [comment]
I threw up a demo of the problem here, perhaps I'm doing something stupid, or maybe I'm running the tests differently from you (I'm not using rake).  In the README are step by step instructions.  The funny thing is that minitap and tapout are working great and doing some nice formatting, but its formatting its own error.

https://github.com/kswope/minitap_rails_test

**Comment by trans** [comment]
I tried out the new version on the project you provided, and it looks promising. Could you give it a try?

**Comment by kswope** [comment]
Works for me now.  I appreciate it.

Just a heads up.  As I was screwing around I noticed that if the minitap gem is required (in Gemfile)

```
gem 'minitap'
```

but isn't used by setting (In test_helper.rb)

```
MiniTest::Unit.runner = MiniTest::TapY.new
```

Then you'll get these bizarro errors.  I'm not saying its a bug, just that its really easy get into this situation, and maybe the gem could emit a more meaningful error to spare you some bug reports.

```
  1) Error:
test_the_truth(UserTest):
NoMethodError: undefined method `before_test' for #<Test::Unit::Runner:0x007ff9fbfade38>
    /Users/kevin/.rvm/gems/ruby-1.9.3-p362/gems/minitap-0.4.0/lib/minitap.rb:556:in `before_test'
    /Users/kevin/.rvm/gems/ruby-1.9.3-p362/gems/minitap-0.4.0/lib/minitap.rb:568:in `before_setup'

2) Error:
test_the_truth(UserTest):
NoMethodError: undefined method `after_test' for #<Test::Unit::Runner:0x007ff9fbfade38>
    /Users/kevin/.rvm/gems/ruby-1.9.3-p362/gems/minitap-0.4.0/lib/minitap.rb:563:in `after_test'
    /Users/kevin/.rvm/gems/ruby-1.9.3-p362/gems/minitap-0.4.0/lib/minitap.rb:574:in `after_teardown'
```

**Comment by trans** [comment]
Ok. Thanks. I'll fix it. Unfortunately Bundler loads everything listed in the Gemfile whether it is used or not.

**Comment by trans** [comment]
Should be fixed in next release. 

Thank you for your help on this! Your input has made a big difference for this project.
