### ISSUE TITLE
Support for Minitest 5.x?

### ISSUE THREAD

**Issue by brandonweiss** [rubyworks/minitap#4]

**Comment by trans** [comment]
Wonderful, _another_ new Minitest API. 

I'll work on it sometime in the next couple of weeks. Thanks for the kick in the pants.

**Comment by brandonweiss** [comment]
Hah. Yeah, they do seem to change up things quite a bit. But, although I don't have much experience with the Minitest code base, the latest changes do seem to be an improvement internally.

No worries, I was just curious if that was on your radar. Thanks!

**Comment by trans** [comment]
I just pushed preliminary support for Minitest 5 to master. Looks good so far, but I still need to look at `minitest/spec` to make sure spec output is optimal. Then once I figure out how to test both v4 and v5 via Travis CI, and tests pass, I'll release.

**Comment by doabit** [comment]
@trans I found the gem can't work with rails 4.1.0.beta and minitest 5.0.8, i got error

``` ruby
=> ruby -Itest test/models/post_test.rb - --tapy
/Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/bundler/gems/minitap-a64c4e0cf87d/lib/minitap/minitest5.rb:810:in `<module:Minitest>': superclass mismatch for class TapY (TypeError)
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/bundler/gems/minitap-a64c4e0cf87d/lib/minitap/minitest5.rb:15:in `<top (required)>'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:239:in `require'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:224:in `load_dependency'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:239:in `require'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/bundler/gems/minitap-a64c4e0cf87d/lib/minitest/minitap_plugin.rb:14:in `plugin_minitap_init'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:64:in `block in init_plugins'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:62:in `each'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:62:in `init_plugins'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:111:in `run'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:46:in `block in autorun'
```

**Comment by trans** [comment]
Hi, I haven't released the newest version yet that would fix this. You can try vendoring it in your Gemfile with, e.g. `:git => git@github.com:rubyworks/minitap.git`. I'll try to make some time today to get this polished off and released. Thanks.

**Comment by doabit** [comment]
I used the master branch, `gem 'minitap', github: 'rubyworks/minitap'`, never mind, i'm only testing minitest 5, thanks.

``` ruby
=> rake test - --tapy
invalid option: --tapy
```

**Comment by trans** [comment]
Ok. I just released v0.5.0. I made a decision to only support Minitest 5+ from here on out. To use Minitest 4 or older be sure to specify Minitap 0.4~.

Given that Minitest 5 is a large API departure from MiniTest 4, there will assuredly be some issues left to fix, and a v0.5.1 will be coming forthwith, so please keep up the great issue reporting. Thanks!

**Comment by trans** [comment]
I've update https://github.com/rubyworks/tapout/wiki/Quick-Start too btw, but I still need to investigate how using the new version effects usage with Rake.

@doabit Did you try:

```
TESTOPTS="- --tapy" rake -q test  
```

**Comment by doabit** [comment]
@trans Thanks, `TESTOPTS="- --tapy" rake -q test` should be right, but it also got error like `ruby -Itest test/models/post_test.rb - --tapy`

``` ruby
Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/bundler/gems/minitap-c936c9603b3b/lib/minitap/minitest5.rb:810:in `<module:Minitest>': superclass mismatch for class TapY (TypeError)
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/bundler/gems/minitap-c936c9603b3b/lib/minitap/minitest5.rb:15:in `<top (required)>'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:239:in `require'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:224:in `load_dependency'
    from /Users/doabit/Sites/test/rails/tmp/minit/rails/activesupport/lib/active_support/dependencies.rb:239:in `require'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/bundler/gems/minitap-c936c9603b3b/lib/minitest/minitap_plugin.rb:14:in `plugin_minitap_init'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:64:in `block in init_plugins'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:62:in `each'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:62:in `init_plugins'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:111:in `run'
    from /Users/doabit/.rbenv/versions/2.0.0-p247/gemsets/4.1.0.beta/gems/minitest-5.0.8/lib/minitest.rb:46:in `block in autorun'
```

**Comment by doabit** [comment]
I have tested again, if don't use rails, it can work well.

``` ruby
ruby -Itest test/main_test.rb - --tapy | tapout dot
Started w/ Seed: 50977
.F

1. FAIL fail test

    Minitest::Assertion

    Failed assertion, no message given.

    test/main_test.rb:9
           06   end
           07
           08   it "fail test" do
        => 09     assert false
           10   end
           11 end


Finished in 0.005s (425.351 test/s, 0.002351s avg.)

2 tests: 1 pass, 1 fail, 0 errs, 0 todo, 0 omit
```

**Comment by trans** [comment]
Ok, so it's something going with the Rails setup. That helps. One thing left to try before I have to dig in with Rails. I just pushed a new master that has no vestigial v4 code. I'm thinking maybe Rails somehow was loading both the v5 and v4 code and thus causing the superclass mismatch. I'm not sure --just a guess, but it's worth a shot. Could you try one more time in your Rails project, making sure to use the git repos master branch?

**Comment by doabit** [comment]
Great :+1: ,  it  works well now. thanks

**Comment by doabit** [comment]
Btw, because the new version use `TESTOPTS="- --tapy" rake -q test` not `rake -q test | tapout`, so it can't work with spring or zeus, i think if possible, should change `TESTOPTS="- --tapy" rake -q test` to `rake -q test -tapy | tapout`, thanks.

**Comment by trans** [comment]
I'm not sure if it is possible, Rake is parsing the options and I am not sure if there is a way to pass them on as test opts. Even adding an initial `-` before the `--tapy` doesn't seem to do anything different. At this point the only approach I can think of is editing the test options in the Rakefile itself. e.g. 

``` ruby
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "lib"
  t.test_files = FileList['test/test*.rb']
  t.verbose = false
  t.options = "- --tapy | tapout #{ENV['rpt']}"
end
```

Then do:

```
$ rpt=progress rake test
```

Would that work with spring or zeus?

**Comment by trans** [comment]
Oh, if you do:

``` ruby
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "lib"
  t.test_files = FileList['test/test*.rb']
  t.verbose = false
  t.options = "- --tapy"
end
```

You should be able to do:

```
$ rake test | tapout progress
```

**Comment by doabit** [comment]
@trans I add another way to use it,

``` ruby
require "minitest/minitap_reporter"
Minitest::MinitapReporter.use 
```

Now, it can work with rails, guard and spring.

``` ruby
rake test | tapout
```

guard-minitest:

``` ruby
guard :minitest, cli: ' | tapout pretty' do
 #...
end
```

spring:

``` ruby
spring rake test | tapout pertty
```

**Comment by trans** [comment]
I think this issue is now resolved. (In fact, I need to backport a couple of features to the 0.4.x series so people still using Minitest 4 can use them.)

**Comment by trans** [comment]
Everything ok @brandonweiss?

**Comment by brandonweiss** [comment]
Yep, I was just cleaning up my issues queue and you mentioned that the issue was resolved.
